version: '3'
services:

  # Portainer UI
  if_mgt:
    image: portainer/portainer
    container_name: if_mgt
    ports:
        - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  # MongoDB
  if-db:
    container_name: if_db
    restart: always
    image: mongo
    volumes:
      - ./data/ideafunnel:/data/db
    ports:
      - 27017:27017
  
  # Angular/Node.js app
  app:
    restart: always
    image: capcodigital/ideafunnel
    ports:
       - 80:3000
    links:
      - if-db
    depends_on:
      - if-db