version: '3'
services:

  if-mgt: # Portainer Container Management
    image: portainer/portainer
    container_name: if-mgt
    ports:
        - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  if-db:
    container_name: if-db
    restart: always
    image: mongo
    volumes:
      - ./data/ideafunnel:/data/db
    ports:
      - 27017:27017

  if-app:
    container_name: if-app
    restart: always
    image: capcodigital/ideafunnel
    ports:
       - 3000:3000
    links:
      - if-db
    depends_on:
      - if-db